language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
env:
  global:
  - SSH_KEY="id_rsa"
  - GIT_NAME="Aaron Edwards (CI)"
  - GIT_EMAIL="mr.amedw@gmail.com"
  - SOURCE_DIR="dist"
  - DEPLOY_BRANCH="master"
before_install:
- openssl aes-256-cbc -K $encrypted_baf88b1a632e_key -iv $encrypted_baf88b1a632e_iv
  -in id_rsa.enc -out id_rsa -d
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
