language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
env:
  global:
    secure: ArJkDLWzsjUqciWuCldyjIF/+ffXU9uVNV9UOK4sUWyykxwNkN5ygweKBOiwkfy/wJmvZOoJaR83a8EJShQlyDmxFX5YcSc/owrHNzOQlq/wkjMY1dBcvJEDUEeSDqSE70jc6li0J10avkZHJx+AAxfmtcBjP8GDNMTlQyxSzhsieFsD9b+QWH5zKxpFaJmz+Ia0MTNr0o74SGCTk8bOyDX1dsVVQywid8/d7zo5AQqO13d5C/5EFNIg7awIbstsLeaPRKMRheXcjyeuJ/77CdhkJaTsnyDh8WOfskjneyF7OcmOmXHdSj7XB/iIUSOWAlYm317dg6+ijPoKxPSCn1cUxwgKN/UsVJIyza3b1tWVA6TZiCC7ejSlVI3lgzPlqHoXdV2VBPoQpN9+IoGZ6yJoEx5124ZrK2WxHf9n3E+HmMY9EhLACwLjIEpkqoi//lVbHLqWIBeXI/jM07YWuZDEc9yza3blJuzPoLLN5Hevu1hz0tHCSOZwmTaMsEAnwottSJt5gOSj4GUaFUcJkpFaiJOTTywb62Y8mYpfbkbSe7U2UVE7FnTqKzuFu9ne/fq3jxxmH6EEApvK57ski+D8Lq/gk82XrYsCYtX1HGWCHjQ+pkjk1o3NlHQAW0o0wgEdkFAqmbtNhE/hl9wo90iN+Tmvndv3NX7IGwq0L6U=
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy:prod
  on:
    branch: master
